
trigger: none
# - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: TerraformValidate
    jobs:
      - job: TerraformValidateJob
        continueOnError: false
        steps:
          - task: PublishBuildArtifacts@1
            inputs:
              TargetPath: '$(System.DefaultWorkingDirectory)/terraform-files'
              ArtifactName: 'terraform-files-out'
              publishLocation: 'pipeline'
          - task: TerraformInstaller@0
            displayName: Terraform install
            inputs:
              terraformVersion: 'latest'
          - task: TerraformCLI@0
            displayName: Terraform init
            inputs:
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-files'
              backendType: 'azurerm'
              backendServiceArm: 'aks-terraform-svc-con'
              backendAzureRmSubscriptionId: 'bedd05d0-ed0c-45f5-9fe1-fc38a22ead10'
              backendAzureRmResourceGroupName: 'tfstateraj'
              backendAzureRmStorageAccountName: 'tfstateraj'
              backendAzureRmContainerName: 'tfstateraj'
              backendAzureRmKey: 'aks-terraform.tfstate'
              allowTelemetryCollection: false
          - task: TerraformCLI@0
            displayName: Terraform Validate
            inputs:
              command: validate
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-files'
              allowTelemetryCollection: false