apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-nginx
  name: app-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-nginx
    spec:
      containers:
      - image: aksclusterdevacr.azurecr.io/aznginxcustom
        name: nginx
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: app-nginx-lb-svc
  labels:
    app: app-nginx-svc
spec:
  type: LoadBalancer
  selector:
    app: app-nginx
  ports:
  - port: 80
    targetPort: 80